<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for apiexception</title>
  </head>
  <body>
    <h1>Links for apiexception</h1>
<a href="https://files.pythonhosted.org/packages/69/32/d2bbd1fe6e6baee5fd12fd1a119e0ceefa08cd08fa9e14bdeebd26166efb/APIException-0.1.0-py3-none-any.whl#sha256=1814e45f31c54cf9fdc12bfbb0e96e04ee2dad64a7e9c7885038ed6664be0d17" data-requires-python="&gt;=3.7" data-dist-info-metadata="sha256=398fa4b0a9304bb4ae86d62a47ebb479b7e0a4666928c86ef91b88e51fbf90df" data-core-metadata="sha256=398fa4b0a9304bb4ae86d62a47ebb479b7e0a4666928c86ef91b88e51fbf90df">APIException-0.1.0-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/94/81/da84f5a11ae7e344612f8e37387844500b249633897d7aad1deb2bf0c920/APIException-0.1.0.tar.gz#sha256=b92f25e2abd4bf5f339745030ea35e661b76eeb49c918ebc303c7e9922bdd33c" data-requires-python="&gt;=3.7" >APIException-0.1.0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/93/af/6f8c4c450260ffe8b7d8b6c005536884343e5261449bfa107ac97b55c6ce/APIException-0.1.1-py3-none-any.whl#sha256=84937ebea58efc22767d422e8ce4b8370e1b825eec08cbd4268dad29419baa54" data-requires-python="&gt;=3.6" data-dist-info-metadata="sha256=062e00d745242995e0c2f1380f3ff2950b602d6fddb400716c01959f10f7e2b3" data-core-metadata="sha256=062e00d745242995e0c2f1380f3ff2950b602d6fddb400716c01959f10f7e2b3">APIException-0.1.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/84/ca/5b60eb35190ba08161096f9830f5fd604224c1bf02494a3006dd68399442/APIException-0.1.1.tar.gz#sha256=6a16fd3cdc05a06e3ea0e0541d0b75f45eabb5b8b6c1fd66693a5c3a0103c211" data-requires-python="&gt;=3.6" >APIException-0.1.1.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/b5/5f/a96593cbea27d85135a35c68236ba3a611b14632563aee3dceec3010d4f9/APIException-0.1.2-py3-none-any.whl#sha256=611f08f84d3d3bfcbd3e7c9782e11c4bdec62f07eca2bf4e80217f59ad275d5c" data-requires-python="&gt;=3.6" data-dist-info-metadata="sha256=210803b12e262f0e76767b74d6974031bf3749c41142ac7ae8ee8b4eeec43b7b" data-core-metadata="sha256=210803b12e262f0e76767b74d6974031bf3749c41142ac7ae8ee8b4eeec43b7b">APIException-0.1.2-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/ae/c8/8bef9119e43de273f401ff52164332db5d551c24d34b9e5489bc35e9807f/APIException-0.1.2.tar.gz#sha256=a82206f8c738292fe0fb9e0d7d683f786ed9a05f55c0c4f81f0c0fd703f4531b" data-requires-python="&gt;=3.6" >APIException-0.1.2.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/d7/93/8ab36255401448c403b3dfdbcc42e4cd50413f4fe896126434240bec50b7/APIException-0.1.4-py3-none-any.whl#sha256=85e1f4760f185a5aaed1c3190d26818f871981d57fa7b7fbfabfcdf12eda171d" data-requires-python="&gt;=3.6" data-dist-info-metadata="sha256=c310c7c70f3de16eb69045e41032d6a03c469b0e6223065813f5ff1e3c1b0575" data-core-metadata="sha256=c310c7c70f3de16eb69045e41032d6a03c469b0e6223065813f5ff1e3c1b0575">APIException-0.1.4-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/1a/d7/79f4fb6033821f47920b403254a991ce169dcd86f953f777f84e6fb90d5e/APIException-0.1.4.tar.gz#sha256=a346317f15ff0779cd25451a12b5b3c16cf61eee5033dc680e63c19f78559b13" data-requires-python="&gt;=3.6" >APIException-0.1.4.tar.gz</a><br />
</body>
</html>
<!--SERIAL 25952762-->