<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for django-exception-logger</title>
  </head>
  <body>
    <h1>Links for django-exception-logger</h1>
<a href="https://files.pythonhosted.org/packages/6b/7e/a914c4e8c22a1882c257d1d68dc227632e47936ba424fbbd790920bfd7d8/django-exception-logger-0.1.3.tar.gz#sha256=d95e92d329988867a8c02da33244cacdd02661c8d9d33eb3a8c58d6e3e972956" >django-exception-logger-0.1.3.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/96/be/6a886327cf7d7db275933830000f2ecec60d7d52d40ce640fd305c8a5e9e/django_exception_logger-0.1.3-py3-none-any.whl#sha256=2bc53cceebaa35ddcd732df754bf58200867058a0515f6fa05d4255770463e06" data-dist-info-metadata="sha256=026f025c2595ad663e5cdc9a2322bc2600d6d24edaa7f7f7c94b6f817457c053" data-core-metadata="sha256=026f025c2595ad663e5cdc9a2322bc2600d6d24edaa7f7f7c94b6f817457c053">django_exception_logger-0.1.3-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/9b/00/c151a88f0efa777ba194b65fecc45833eb6e961e9a0a5916fedef0b8e987/django-exception-logger-0.1.4.tar.gz#sha256=252eeaa0a9e85c011c5eac0e6b84a6ec74b312ed36e9a8f89addb5ecc326a52d" >django-exception-logger-0.1.4.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/ec/41/d66599472347aa20631ac8656de5033889ec4189b86c18d5b4c01b2ed74b/django_exception_logger-0.1.4-py3-none-any.whl#sha256=60fc916bf5c74a2a7533f8b1c532ac78d8b0b38e4cb451ce474a64835bf6e6f0" data-dist-info-metadata="sha256=0fc550e46adea35a55932299d0c4fb8a6cb4222e1d39ae86a0df4c3556443092" data-core-metadata="sha256=0fc550e46adea35a55932299d0c4fb8a6cb4222e1d39ae86a0df4c3556443092">django_exception_logger-0.1.4-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/aa/78/84f141c2e9065d1ceea550b969fb20a3aa0907d3cf02e0e1488ecaa7bc47/django_exception_logger-0.1.5-py3-none-any.whl#sha256=263c3a2f0e2c2dff720fa6dcab63a7ed04a70e3cf8d9f43a0989e1a73a901284" data-dist-info-metadata="sha256=38178db05e3749af5da30ed9384866c7e21aeb7dd90e1879a075fe919ba82ae3" data-core-metadata="sha256=38178db05e3749af5da30ed9384866c7e21aeb7dd90e1879a075fe919ba82ae3">django_exception_logger-0.1.5-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/fe/f4/1f025ccbe1f01d2f95d261253f53fa79872fe60814abb2493d65c07d1814/django-exception-logger-0.1.6.tar.gz#sha256=6d5aa5dbc347559d8d4f10669e67507667f078be29c1fb58f69a0a4767c2a5f9" >django-exception-logger-0.1.6.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/19/f6/b8725fde527cfd57e615196ea1762e5bb880c33ede545e8582868d1b3ef9/django-exception-logger-0.1.7.tar.gz#sha256=db75fe692c52e54f1a3cc362275c0667ca3b1f6cad8672d46ee97b0115ee88f9" >django-exception-logger-0.1.7.tar.gz</a><br />
</body>
</html>
<!--SERIAL 26105840-->