<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for django-error-report-2</title>
  </head>
  <body>
    <h1>Links for django-error-report-2</h1>
<a href="https://files.pythonhosted.org/packages/27/81/b6418317ef2dded58cbde2aa8d0eb286f42a143cef3fdc8efd1c4f83ac57/django-error-report-2-0.4.0a0.tar.gz#sha256=a915aa52fdee615f6cf3265590ba2bb50baa8194a3c4c23c2dbd4ce95bd2bfaf" >django-error-report-2-0.4.0a0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/cf/16/8bdab9654b24bb1658872ef5982d21f2fbdeedd97b2fad83aac43fe738b5/django_error_report_2-0.4.0a0-py3-none-any.whl#sha256=3a105c50e0f616f15ef8cec0c449e02e1220ab118f8473372a71d3d0dd6d862c" data-dist-info-metadata="sha256=bcb34a79746cb66157d7c238ba36f8abaafe5ad1d3aeebe799be60f893bc52dc" data-core-metadata="sha256=bcb34a79746cb66157d7c238ba36f8abaafe5ad1d3aeebe799be60f893bc52dc">django_error_report_2-0.4.0a0-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/ec/32/a326e4f898a7c0c754e34a29c69e8126f7e403aba032efbb1ee6f851d1f9/django-error-report-2-0.4.0a1.tar.gz#sha256=f17820c52d6215731e61f9db4c46ae3645441cc8ee1437ce1783591982624f7e" >django-error-report-2-0.4.0a1.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/38/6b/de2a0bc8418b67fb585c3cb71d6a7fe00f60770ac73cebc73831fed88432/django_error_report_2-0.4.0a1-py3-none-any.whl#sha256=7f112d6cfb8dc43bfba2938523489bdf3a59d731e0814150549f79f4340804a9" data-dist-info-metadata="sha256=ebfaaf8f8dc9f767abd878f034a0f451d287b013d4951a7215c7c013bc4c2a62" data-core-metadata="sha256=ebfaaf8f8dc9f767abd878f034a0f451d287b013d4951a7215c7c013bc4c2a62">django_error_report_2-0.4.0a1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/06/68/6f74a14e9784a57ee9ca886fce3a4b1f46295cc9c08e398bb8f003f9e928/django-error-report-2-0.4.0.tar.gz#sha256=5c0c933c9b679bdb7b75f463f6818331951653b56b7e5edbe138e08ad146afe4" >django-error-report-2-0.4.0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/33/89/83b1e3da64bd2b6450810d072402ebcb8d92ef7868cd8fd86543b1bcbf61/django_error_report_2-0.4.0-py3-none-any.whl#sha256=1b6634ef9bfb04efba9d2dd04a0671825de95aed2469a5f1fdd32ffa8be0c664" data-dist-info-metadata="sha256=846bcf6b2ca1de549fce3477d4edfde497a32a9b7d116726214cb60cdb228606" data-core-metadata="sha256=846bcf6b2ca1de549fce3477d4edfde497a32a9b7d116726214cb60cdb228606">django_error_report_2-0.4.0-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/f2/89/a62f7e5b4a06e7cc31b8f2ffca193e59bc2b42340a45c45efe09ee05ac0a/django-error-report-2-0.4.1.tar.gz#sha256=77affbff08d256031dcbfd4ef6861686e48e78dec078d7e1e8759ba16d3aa14f" >django-error-report-2-0.4.1.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/3d/7e/66ef1e09d23b6a45beb65f60b9fa0dce05240766d021db9fb4be3ca0f50b/django_error_report_2-0.4.1-py3-none-any.whl#sha256=73e691a78d0803fe05a0429be2e8e02e85956faf15068b377fb4adb1f72b7774" data-dist-info-metadata="sha256=3f6fc51f3e32541b25bd06aec30fe749d6b54c4edf69993b975fe0683ee7877d" data-core-metadata="sha256=3f6fc51f3e32541b25bd06aec30fe749d6b54c4edf69993b975fe0683ee7877d">django_error_report_2-0.4.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/37/56/20a47d27df687238ff58c2ad74fc3856756de61d5d6dc2924270fe8b7d05/django-error-report-2-0.4.2.tar.gz#sha256=603e1e3b24d01bbfeab6379af948893b2b034031c80fa8b45cf1c4735341c04b" >django-error-report-2-0.4.2.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/9f/df/b0985db6c0e3feadf054b3f2c9df281d8eb7463a32a903a549ae21233eb7/django_error_report_2-0.4.2-py3-none-any.whl#sha256=1dd99c497af09b7ea99f5fbaf910501838150a9d5390796ea00e187bc62f6c1b" data-dist-info-metadata="sha256=94d150e8450cb68b02514e6ef31d880c33f7b94aae1853425c40dbff1aa106ec" data-core-metadata="sha256=94d150e8450cb68b02514e6ef31d880c33f7b94aae1853425c40dbff1aa106ec">django_error_report_2-0.4.2-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 19189833-->