<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for drf-common-exceptions</title>
  </head>
  <body>
    <h1>Links for drf-common-exceptions</h1>
<a href="https://files.pythonhosted.org/packages/65/ae/3e4901527628d990cdde222d9e886fad0404762c23125e1b82434d3c8176/drf-common-exceptions-0.1.0.tar.gz#sha256=f7051b1b24e465ae798f645743bdbcd9c35466cf0170ccf3fa2c0fc75b140de2" data-requires-python="&gt;=3.6,&lt;4.0" >drf-common-exceptions-0.1.0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/ec/f3/ac717f1f8d3d7b55f98f4c3b448debce9773241a69d4a5276a57c4ffe0d5/drf_common_exceptions-0.1.0-py3-none-any.whl#sha256=c89ce44837db81b975fc90a5fcea400a468733d333f97295ddf0e2ac5ccb3d42" data-requires-python="&gt;=3.6,&lt;4.0" data-dist-info-metadata="sha256=de9e60093ee4e77e5724a526630c590cf0e3de4f6c2fc8e31bc0bcf7af7c5d6e" data-core-metadata="sha256=de9e60093ee4e77e5724a526630c590cf0e3de4f6c2fc8e31bc0bcf7af7c5d6e">drf_common_exceptions-0.1.0-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/29/08/c66c1ee0b2a71898a8e99a820308e1008dc1c60ccabcc4148997e5ae2ef5/drf-common-exceptions-0.1.1.tar.gz#sha256=c9224deb7b5bd1558828effd06bc0dee81434bae4fa08a10b49c57c02dc1911b" data-requires-python="&gt;=3.6,&lt;4.0" >drf-common-exceptions-0.1.1.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/fa/7b/da4ec6464bd5e52c841db81f2727888f16e5c168ff878b96217003267340/drf_common_exceptions-0.1.1-py3-none-any.whl#sha256=7b7ce27f54a58188c24992645465a98d8a5cbb4c7afe8c3b7615b76cecd2c6b8" data-requires-python="&gt;=3.6,&lt;4.0" data-dist-info-metadata="sha256=21f24a415e518bc1524f81bf535c1bc068eba9fd3de4b18d96db66dd48da901f" data-core-metadata="sha256=21f24a415e518bc1524f81bf535c1bc068eba9fd3de4b18d96db66dd48da901f">drf_common_exceptions-0.1.1-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 4889072-->