<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for easyexception</title>
  </head>
  <body>
    <h1>Links for easyexception</h1>
<a href="https://files.pythonhosted.org/packages/26/72/c3ab4e8567eb7219c9c1d7d315da5cfc5522bca941d6f32f045325b1bd22/easyexception-0.0.2-py3-none-any.whl#sha256=694e428027c2812e0c51cc94802c45ea427a1d9a78f4844d24dcfbae220468a3" data-requires-python="&gt;=3.0" data-dist-info-metadata="sha256=659b8fad78d5f362b539c0655be2f001bbeeef9abe34e6badbc5faf4515b45ce" data-core-metadata="sha256=659b8fad78d5f362b539c0655be2f001bbeeef9abe34e6badbc5faf4515b45ce">easyexception-0.0.2-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/4b/96/408d941c8dbf754ab81c0efa6fb4fd8ae660567310772d5be8335d6d57f6/easyexception-0.0.2.tar.gz#sha256=40de257ec8091ca13b0a43f9cf677a77e38c07092ad87399438bf1ca784ef05f" data-requires-python="&gt;=3.0" >easyexception-0.0.2.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/ac/ce/e0f66cd8eaf3c24718f6c22e009b122c39a8b0e0555c7e2387958549910d/easyexception-0.0.3-py3-none-any.whl#sha256=9b0ef887c5f1cca412ca0c873054806e451f96cf02d8f28eba5b1cd191ad1ed8" data-requires-python="&gt;=3.0" data-dist-info-metadata="sha256=cf73695b5e8c9b426a3cdd2c793f2bf310d3e85a2294f0e96bdafbd96dbec440" data-core-metadata="sha256=cf73695b5e8c9b426a3cdd2c793f2bf310d3e85a2294f0e96bdafbd96dbec440">easyexception-0.0.3-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/34/4b/e9c091006003fbae7d8179adef604aea2226b00de4b15701b495f4e493ce/easyexception-0.0.3.tar.gz#sha256=00018ffc1425f92bb75add2048b6629af8d8dd8e8d2697d46c8e25a3c876651b" data-requires-python="&gt;=3.0" >easyexception-0.0.3.tar.gz</a><br />
</body>
</html>
<!--SERIAL 5194466-->