<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for errcallback</title>
  </head>
  <body>
    <h1>Links for errcallback</h1>
<a href="https://files.pythonhosted.org/packages/26/7a/4abbb148721fd022a2bc44bbd5229e36827d659f3e054af91aee020472f6/errcallback-0.0.1-py3-none-any.whl#sha256=63ad023f6f81e323d0bb7f79f0e08e4b1d9d282e9886e1269a163312a0637b9b" data-requires-python="&gt;=3.6" data-dist-info-metadata="sha256=c9aa89760a340f0ff636c915565081c2d1fa93377393305914f79ac9b44fb9de" data-core-metadata="sha256=c9aa89760a340f0ff636c915565081c2d1fa93377393305914f79ac9b44fb9de">errcallback-0.0.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/bc/16/20d2412e2d1810f4b774db38b8d053d9cb166deb8606f585b9aae12214c7/errcallback-0.0.1.tar.gz#sha256=c720420007e694ece4e07c71b54769eee79521eac8bb60e51950a2588785dcaf" data-requires-python="&gt;=3.6" >errcallback-0.0.1.tar.gz</a><br />
</body>
</html>
<!--SERIAL 12081471-->