<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for errornumbers</title>
  </head>
  <body>
    <h1>Links for errornumbers</h1>
<a href="https://files.pythonhosted.org/packages/be/22/d7186c1bb65c610ff82a7382a8b3e8b654fb3b0026ded1bf2f48a329cf06/errornumbers-0.5.tar.gz#sha256=96d3547ab2c41c7a646663a9f9b711bd85354c3eb32243361e1d60604d7b9b81" >errornumbers-0.5.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/bf/41/afdd1e673597fc76d09608743db74e17cca2b31c5036b59b83e62d7055f4/errornumbers-0.6.tar.gz#sha256=5cb0a374fc3f2077066e554605d8e31a036d54553450d49fa0f433f4372bb46f" >errornumbers-0.6.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/c6/54/b0ff3b088a8a350e22dbc46cf9f8deabce6ccca802abccee725c7884626f/errornumbers-0.7.tar.gz#sha256=f310591bee964960493cef74dd16ea515f7364853a353b9f3a8cbcdcf9df7b59" >errornumbers-0.7.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/5f/7a/820739edb6ee0d2218e8d0c22f1a10e446f16190a266eabae8b9ef1614b8/errornumbers-0.8.tar.gz#sha256=4d0c808f22d8bf23ebbda9a401ac28a9d18d163db881f46e6199fb1404b9ebda" >errornumbers-0.8.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/28/dd/783b5ccc4ae6b1dc4f0595deba204a6426289b3a763e9acd46c96aa21d33/errornumbers-0.10.0-py3-none-any.whl#sha256=425cb7492574b4d4cf5cb7d9a2e9532c57f4b66c785ed2429bd5005b3c5a620c" data-requires-python="&gt;=3.9,&lt;4.0" data-dist-info-metadata="sha256=ca762faac50c1d2a1de0f6a9c11fbcb9c2ad44af497a45dccf1b0d6a924d5294" data-core-metadata="sha256=ca762faac50c1d2a1de0f6a9c11fbcb9c2ad44af497a45dccf1b0d6a924d5294">errornumbers-0.10.0-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/e0/26/115b2437792e9f3ab6213f5572451309b4f835e269a92b0ca2c2c116cdad/errornumbers-0.10.0.tar.gz#sha256=dedbcd3fbe21277d98a2328df27dbbf01a0e13d9ca03bd40d53979d2d28023b1" data-requires-python="&gt;=3.9,&lt;4.0" >errornumbers-0.10.0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/fd/6c/768f36ad9f122910b59060964abfd607fb3a41c9060fb5f8f420b1e56bd8/errornumbers-0.10.1-py3-none-any.whl#sha256=816c2372fddb87a699bc6ab0b9c1b6df844012810cbdba91dc40a05de03afc03" data-requires-python="&gt;=3.9,&lt;4.0" data-dist-info-metadata="sha256=18119cf6c97b4364a3bff36d8b7e9612bea8efedd5fb143c44fcd34f528b63ec" data-core-metadata="sha256=18119cf6c97b4364a3bff36d8b7e9612bea8efedd5fb143c44fcd34f528b63ec">errornumbers-0.10.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/a2/7f/be5e1259f48de350db9339bdefe20de73aafbba6f30f40d07d2507cdbf6a/errornumbers-0.10.1.tar.gz#sha256=5c9f6f71679a172b617af5f6cfdc2fdcde93ddae583e0232014de6288d75118d" data-requires-python="&gt;=3.9,&lt;4.0" >errornumbers-0.10.1.tar.gz</a><br />
</body>
</html>
<!--SERIAL 11757740-->