<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for exception-logger</title>
  </head>
  <body>
    <h1>Links for exception-logger</h1>
<a href="https://files.pythonhosted.org/packages/97/01/83f4c628e7cb2719e79791d94477891b5ba4010abc24eea37cfe2c26f62e/exception_logger-0.1-py3-none-any.whl#sha256=b07c730b0b0033f669db545b8bf59c50c70cfa86c84155bc5a1c561cb31bb7dc" data-dist-info-metadata="sha256=b3f4c0fe07f4a74bed3b4fd1fbd210e4667fd0629208f5740b958b33e141c517" data-core-metadata="sha256=b3f4c0fe07f4a74bed3b4fd1fbd210e4667fd0629208f5740b958b33e141c517">exception_logger-0.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/88/96/05224c03971358ee3c3974274b44fbb814cc3e6e44fd138211406cbd2a30/exception_logger-0.1.tar.gz#sha256=75c7bdcfee2979608504400ede394720084677aa38dc26cf8e51c833f9dd9bc8" >exception_logger-0.1.tar.gz</a><br />
</body>
</html>
<!--SERIAL 24447552-->