<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.2">
    <title>Links for fastapi-openapierrors</title>
  </head>
  <body>
    <h1>Links for fastapi-openapierrors</h1>
<a href="https://files.pythonhosted.org/packages/3d/49/6427c124678eb2044f110d7bb14dc5c7954bec6f9acf4e009448e7bddc28/fastapi-openapierrors-0.9.0.tar.gz#sha256=4a053f84ac99097c15a5bf370c407c4fdbcdefd3f5967b97cc2f2d4dec4d39da" >fastapi-openapierrors-0.9.0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/04/01/b89238396b943ced9e1e39f68523b75975b2b3167584826205d94beae702/fastapi_openapierrors-0.9.0-py3-none-any.whl#sha256=aefa0769a333cf73c406d01e5188b1c1427a7e960c440491b8d46af67964360b" data-dist-info-metadata="sha256=9e2db8cdcb7f41f51a8fb8b081b8ffe2e7a245ef6d3fdf231bdd8a0d3591db88" data-core-metadata="sha256=9e2db8cdcb7f41f51a8fb8b081b8ffe2e7a245ef6d3fdf231bdd8a0d3591db88">fastapi_openapierrors-0.9.0-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 11385520-->