<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.3">
    <title>Links for odoo-addon-partner-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-partner-exception</h1>
<a href="https://files.pythonhosted.org/packages/52/05/61fb525739aa702bf0646b243a1121323bc20be831c25fdf215609a0db94/odoo_addon_partner_exception-15.0.1.0.0.3-py3-none-any.whl#sha256=bc5a0e531e84f44ba6f8929469cb1d3db1eaa2367257ab9e54f83f6444670cd0" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=c4682f73dc5aa4fbef6ae9071c0cf9756736e9c3dc3dfe76461197ab4b6107c2" data-core-metadata="sha256=c4682f73dc5aa4fbef6ae9071c0cf9756736e9c3dc3dfe76461197ab4b6107c2">odoo_addon_partner_exception-15.0.1.0.0.3-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/e7/9d/0d8eb15bb9eaa8d16ed39c0aaca536b3879b61a7615dc7cb4f96d5599b53/odoo_addon_partner_exception-15.0.1.0.0.4-py3-none-any.whl#sha256=f3fa39d60ce810b444079a0bf72bc186c45ac8bb89ee3166eb4b600a5a5c3f7a" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=dccb7e82a855a8e3d10b60b9c599923d01d5d912e227215a958e58cfcc77879c" data-core-metadata="sha256=dccb7e82a855a8e3d10b60b9c599923d01d5d912e227215a958e58cfcc77879c">odoo_addon_partner_exception-15.0.1.0.0.4-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/a7/d2/b7c0593dcc3a92ba2c3fedb99ab481c3af4ae20aa2c79e4be3b8f4b848a5/odoo_addon_partner_exception-15.0.1.0.0.6-py3-none-any.whl#sha256=294d457f695bfedb0cbee09f4a1b4fd85f831a0211ce57120afe1c2d0186a529" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=a92eb14d52867f649ed6e641531a7a434e6b09935c09ef163de48b28e5258bd5" data-core-metadata="sha256=a92eb14d52867f649ed6e641531a7a434e6b09935c09ef163de48b28e5258bd5">odoo_addon_partner_exception-15.0.1.0.0.6-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 20117291-->