<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.2">
    <title>Links for odoo13-addon-sale-exception-financial-risk</title>
  </head>
  <body>
    <h1>Links for odoo13-addon-sale-exception-financial-risk</h1>
<a href="https://files.pythonhosted.org/packages/33/23/7dfdf5c4c255dd732ad2400396e5e86e2759c5d195f7b479c6a35b4a5ada/odoo13_addon_sale_exception_financial_risk-13.0.1.0.1.dev2-py3-none-any.whl#sha256=7445b6f3b79b5450db1618ca4a79848e744aa7e02815e6d21e5293c81de65be6" data-requires-python="&gt;=3.5" data-dist-info-metadata="sha256=915556f78550570d8ff5a7606b1606185d2d84bcd9e64278ec1d4aa6fbb18df2" data-core-metadata="sha256=915556f78550570d8ff5a7606b1606185d2d84bcd9e64278ec1d4aa6fbb18df2">odoo13_addon_sale_exception_financial_risk-13.0.1.0.1.dev2-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/a3/b8/796b98d599f0c19c573c93a801d60c7b93360f83823fb8326dd7c46c1473/odoo13_addon_sale_exception_financial_risk-13.0.1.0.1.dev3-py3-none-any.whl#sha256=d3aac65d6fb76946d01b98f622b6ebd584836a978d1e371a18242cd4a864e8bd" data-requires-python="&gt;=3.5" data-dist-info-metadata="sha256=1125233d3191e0ef5838afa60d45a9340961039798c94b24ad3514a3778fb8b0" data-core-metadata="sha256=1125233d3191e0ef5838afa60d45a9340961039798c94b24ad3514a3778fb8b0">odoo13_addon_sale_exception_financial_risk-13.0.1.0.1.dev3-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 19576806-->